### ISSUE TITLE
Running on Windows yields 0 rows

### ISSUE THREAD

**Issue by julesdc** [relikd/abcddb2vcard#3]
Tried running directly on a AddressBook-v22.abcddb file that was sent to me and I can't get any results from the sqlite DB. Also wondering if there is some addition you could make to read the individual xxx.abcdp files?

**Comment by relikd** [comment]
Interesting... is it a problem with my tool or is the DB empty? Can you try an open the db in an sqlite3 application and see if it shows anything?

```sh
sqlite3 file.abcddb "SELECT * FROM ZABCDRECORD;"
```
should print a list or people. ... maybe the `.abcddb-wal` and `.abcddb-shm` files are missing? They hold the DB changes until they are persisted.

...

As to your other question. Sure, reading the abcdp files should be easy. They are simple plist files. I may add functionality for reading `abcdp` files some time in the future (when I find free time).

Meanwhile you can use this snippet to export your contacts:

```py
import plistlib

with open('file.abcdp', 'rb') as fp:
    data = plistlib.load(fp)
    print(data)
```

**Comment by julesdc** [comment]
Firstly - your tool is great!

This helped - thank you. I queried the DB using sqlite3 directly and it looks like theres only 2 records in ZABCRECORD and most of the tables are empty.

I created a little module to read the plist files instead and that really helped - thank you! It is basically the same data as the abcddb file but in key: val pairs.

I am curious how you found the information to map the correct labels to vcf/Apple readable format as I can't really find many resources on it.

E.g. I have a URL that I can't get to parse properly
`label: 'Outlook', values: 'ms-outlook://people/v2/<long hash>?accountKey=<hash>&checksum=<hash>`

**Comment by relikd** [comment]
Mostly due to manually crafting Contacts and exporting them with Apple software. Plus the [Wiki entry](https://de.wikipedia.org/wiki/VCard) and [RFC 6350](https://datatracker.ietf.org/doc/html/rfc6350) on vCard (especially the latter for X.520 handling). Regarding your Outlook URL, what exactly does not work? Maybe it has something to do with X.520 and you have to escape some chars (`,` and `;`) but thats hard to tell without further context.

**Comment by julesdc** [comment]
Yeah there is such a mess of encoding types and x.520 between exporting from OS X, converting to plist, reading in Windows, testing V Cards in Windows/Google calendar, etc....

I think the wiki/RFC entries are clear on the very basics of the file protocol, but trying to reconstruct other OS X tags like X-SOCIALPROFILE, X-ADR, X-ABLabel, et al and get it 'just right' is very difficult without proper docs.

Since this isn't really an 'issue' and more just a discussion, you can close the thread if you'd like :)

Again, thanks for some awesome code and serious expertise in this area. Really saved my skin this past week.
